sonar.projectKey=modulo-inventario
sonar.projectName=Modulo de Inventario - Equipo 6
sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
# Si usan SonarCloud, agreguen también:
# sonar.organization=nombre-de-su-organizacion
